### ISSUE TITLE
change default scheduler from FIFO to RR

### ISSUE THREAD

**Issue by TheSayOL** [syswonder/ruxos#121]
In some cases, the FIFO scheduling policy can lead to bugs. For example, consider a scenario where one thread is continuously polling files. If these files become ready, the thread informs other threads to perform certain actions through IPC, such as pipes. If the files are ready, this thread might enter an infinite loop, preventing other threads from executing. This can happen unless using a different scheduler, like RR, which ensures that all threads get a chance to run.

**Comment by coolyjg** [comment]
Fixed in #124
