### ISSUE TITLE
could not find `arceos` in `os`

### ISSUE THREAD

**Issue by rtczza** [syswonder/ruxos#49]
cargo build:
```
error[E0433]: failed to resolve: could not find `arceos` in `os`
 --> apps/display/draw_map/src/display.rs:5:14
  |
5 | use std::os::arceos::api::display as api;
  |              ^^^^^^ could not find `arceos` in `os`

```
why? how to fix ?

**Comment by rtczza** [comment]
rustc 1.74.0-nightly (2f5df8a94 2023-08-31)

**Comment by coolyjg** [comment]
It seems that `axstd` feature is not enabled.

**Comment by coolyjg** [comment]
You are supposed to run `make A=apps/display/draw_map GRAPHIC=y run`  in the root directory of RuxOS to run this application, instead of using `cargo build` directly, since `arceos` is an internal mod of RuxOS.

**Comment by rtczza** [comment]
`make A=apps/display/draw_map GRAPHIC=y run`  can run program draw_map directly.

but `make A=apps/fs/shell GRAPHIC=y run` , error:
```
[  0.106377 0 ruxruntime::lang_items:14] panicked at modules/ruxfs/src/lib.rs:73:35:
No block device found!
```

In addition, I would also like to ask, since the above are running some applications, how should I run ruxos so that I can do some operations in the system.

**Comment by rtczza** [comment]
run `make A=apps/fs/shell  ARCH=x86_64 LOG=info run BLK=y` 
error:
```
qemu-system-x86_64: -drive id=disk0,if=none,format=raw,file=disk.img: Could not open 'disk.img': No such file or directory
```
 disk.img  where should I look?

**Comment by coolyjg** [comment]
> `make A=apps/display/draw_map GRAPHIC=y run` can run program draw_map directly.
> 
> but `make A=apps/fs/shell GRAPHIC=y run` , error:
> 
> ```
> [  0.106377 0 ruxruntime::lang_items:14] panicked at modules/ruxfs/src/lib.rs:73:35:
> No block device found!
> ```
> 
> In addition, I would also like to ask, since the above are running some applications, how should I run ruxos so that I can do some operations in the system.

For block device, you need to run `make disk_img` first to create a fat32 image. You can see [RuxOS Book](https://ruxos.syswonder.org) for more information. 
Since RuxOS is a unikernel OS, you can't run RuxOS alone, without running any application.

**Comment by rtczza** [comment]
Thanks for the guidance. `apps/fs/shell` is run normal.

**Comment by coolyjg** [comment]
You're welcome. This issue shall be closed.
